import { useParams } from "react-router-dom";
import { useEffect, useState } from "react";

export default function ValidationPage() {
  const { code } = useParams();
  const [receipt, setReceipt] = useState(null);

  useEffect(() => {
    fetch(`/api/validate/${code}`)
      .then(res => res.json())
      .then(setReceipt)
      .catch(err => console.error("Error fetching receipt data:", err));
  }, [code]);

  if (!receipt) return <p>Loading...</p>;

  return (
    <div className="min-h-screen bg-gray-100 flex justify-center py-8">
      <div className="bg-white w-full max-w-lg shadow-lg border border-gray-300">

        {/* Page Title */}
        <div className="p-8 text-center">
          <h1 className="text-4xl font-bold text-gray-800">
            QR Code Validation
          </h1>
        </div>

        {/* VALID Banner */}
        <div className="py-10 text-center">
          <h2 className="text-4xl font-extrabold text-green-600">
            VALID
          </h2>
        </div>

        {/* Receipt Details Table */}
        <table className="w-full border-collapse">
          <thead>
            <tr>
              <th className="border bg-gray-100 p-3 text-left">Attribute</th>
              <th className="border bg-gray-100 p-3 text-left">Value/Details</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border p-3 font-bold text-gray-700">Code</td>
              <td className="border p-3 text-sky-500">{receipt.code}</td>
            </tr>
            <tr>
              <td className="border p-3 font-bold text-gray-700">Description</td>
              <td className="border p-3 text-sky-500">{receipt.description}</td>
            </tr>
            <tr>
              <td className="border p-3 font-bold text-gray-700">Document Date</td>
              <td className="border p-3 text-sky-500">
                {new Date(receipt.document_date).toLocaleString("en-GB", {
                  day: "2-digit",
                  month: "2-digit",
                  year: "numeric",
                  hour: "2-digit",
                  minute: "2-digit",
                  second: "2-digit",
                })}
              </td>
            </tr>
            <tr>
              <td className="border p-3 font-bold text-gray-700">Generated by</td>
              <td className="border p-3 text-sky-500">{receipt.generated_by}</td>
            </tr>
            <tr>
              <td className="border p-3 font-bold text-gray-700">Amount</td>
              <td className="border p-3 text-sky-500">{receipt.amount}</td>
            </tr>
            <tr>
              <td className="border p-3 font-bold text-gray-700">Issued To</td>
              <td className="border p-3 text-sky-500">{receipt.issued_to}</td>
            </tr>
            <tr>
              <td className="border p-3 font-bold text-gray-700">Sub County</td>
              <td className="border p-3 text-sky-500">{receipt.sub_county}</td>
            </tr>
            <tr>
              <td className="border p-3 font-bold text-gray-700">Ward</td>
              <td className="border p-3 text-sky-500">{receipt.ward}</td>
            </tr>
            <tr>
              <td className="border p-3 font-bold text-gray-700">Zone</td>
              <td className="border p-3 text-sky-500">{receipt.zone}</td>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
  );
}
